theme: jekyll-theme-midnight
baseurl: "/HTDark"
maintenance_mode: false
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-archives
  - jekyll-toc
  - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-emoji
  - jekyll-reading-time

paginate: 5
paginate_path: "/page:num/"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      toc: true

markdown: kramdown

kramdown:
  toc_levels: 1..3
  input: GFM
