source "https://rubygems.org"
gem "jekyll", "~> 4.3.0"
gem "minima", "~> 2.5"
gem "jekyll-seo-tag"
gem "jekyll-feed"
gem "jekyll-sitemap"
gem "jekyll-paginate-v2"
gem "jekyll-archives"
gem "jekyll-toc"
gem "jekyll-redirect-from"
gem "jekyll-mentions"
gem "jekyll-emoji"
gem "jekyll-reading-time"
